CREATE TABLE user (
 SEQ        INT NOT NULL AUTO_INCREMENT,
 GOOGLE_USERNAME VARCHAR(20),
 GOOGLE_ID	VARCHAR(100),
 USER_NICKNAME VARCHAR(20),
 USER_PW    VARCHAR(20),
 EMAIL     VARCHAR(20),
 USER_PHONENUM    VARCHAR(20),
 USER_BIRTH   VARCHAR(10),
 USER_GENDER VARCHAR(1),
 USER_ROLE VARCHAR(10),
 AGREE_TO_RECEIVE_EMAIL VARCHAR(1),
 AGREE_TO_RECEIVE_MSG VARCHAR(1),
  PRIMARY KEY(seq)
) ENGINE=MYISAM CHARSET=utf8;

select * from user;
