server:
  port: 9030
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/travel?characterEncoding=utf-8
    username: root
    password: akflfls8dfh115!
        
mybatis:
  type-aliases-package: com.campus.myapp.vo
  mapper-locations: mapper/*Mapper.xml
  
