server:
  port: 8090
  
spring:
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp
  dataSource: #jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/(__1번__)?characterEncoding=utf-8
    username: root
    password: 
  servlet: #파일업로드
    multipart:
      max-file-size: 20MB
      enabled: true
        
  
#mybatis:
# type-aliases-package: com.campus.myapp.vo
# mapper-locations: mapper/*Mapper.xml

