server:
  port: 8090
  
spring:
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp
  dataSource: #jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/travel?characterEncoding=utf-8
    username: root
    password: akflfls8dfh115!
  servlet: #파일업로드
    multipart:
      max-file-size: 20MB
      enabled: true
        
  
mybatis:
 type-aliases-package: com.novicecoders.ontheway.vo
 mapper-locations: mapper/*Mapper.xml

